config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  #resources :posts

  get 'webinary/index'
  get 'services/index'
  get 'jobs/index'
  get 'employees/profile'

  devise_for :visitors
  devise_for :employees
  resources :employees
  devise_for :users
  devise_for :works

  get 'visitors/profile'
  get 'works/profile'
  get 'meetings/index'

  resources :visitors
  resources :works
  get 'home/index', as: 'employee_root'

  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  #establish_connection :adapter => 'postgresql', :database => 'control', :username => 'light', :password => 'p12345678'
  mount_uploader :profile, EmployeeUploader

  #has_attached_file :av
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @current_employee
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :lastname, :login, :password, :email, :phone, :tip, :profile)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :employee_lastname %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :employee_login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :employee_password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :employee_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :employee_phone %>
  </div>

  <div class="field">
    <%= form.label :profile %>
    <%= form.file_field :profile, id: :employee_profile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1><%= employee_signed_in? %><%= @employee_url %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Login</th>
      <th>Password</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.login %></td>
        <td><%= employee.password %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><img src=<%= employee.profile.thumb.url %> ></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Login:</strong>
  <%= @employee.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @employee.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Profile:</strong>
  <img src=<%= @employee.profile.thumb.url %> >
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>