config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  #resources :posts

  get 'webinary/index'
  get 'services/index'
  get 'jobs/index'
  get 'employees/profile'

  devise_for :visitors
  devise_for :employees
  resources :employees
  devise_for :users
  devise_for :works

  get 'visitors/profile'
  get 'works/profile'
  get 'meetings/index'

  resources :visitors
  resources :works
  get 'home/index', as: 'employee_root'

  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  mount_uploader :avatar_file_name, VisitorUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @current_visitor
    @pg = 'visitors/sshow'
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :lastname, :login, :password, :email, :phone, :tip, :education, :occupation, :subsection, :rating, :injob, :outjob, :startmeeting, :endmeeting, :avatar_file_name)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :visitor_name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :visitor_lastname %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :visitor_login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :visitor_password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :visitor_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :visitor_phone %>
  </div>

  <div class="field">
    <%= form.label :tip %>
    <%= form.text_field :tip, id: :visitor_tip %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.text_area :education, id: :visitor_education %>
  </div>

  <div class="field">
    <%= form.label :occupation %>
    <%= form.text_area :occupation, id: :visitor_occupation %>
  </div>

  <div class="field">
    <%= form.label :subsection %>
    <%= form.text_field :subsection, id: :visitor_subsection %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: :visitor_rating %>
  </div>

  <div class="field">
    <%= form.label :injob %>
    <%= form.datetime_select :injob, id: :visitor_injob %>
  </div>

  <div class="field">
    <%= form.label :outjob %>
    <%= form.datetime_select :outjob, id: :visitor_outjob %>
  </div>

  <div class="field">
    <%= form.label :startmeeting %>
    <%= form.datetime_select :startmeeting, id: :visitor_startmeeting %>
  </div>

  <div class="field">
    <%= form.label :endmeeting %>
    <%= form.datetime_select :endmeeting, id: :visitor_endmeeting %>
  </div>

  <div class="field">
    <%= form.label :avatar_file_name %>
    <%= form.file_field :avatar_file_name, id: :visitor_avatar_file_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitors/_sshow.html.erb
<table cellpadding="0" cellspacing="0" width="900" align="center">
<tr>
<td class="left_col_profile" valign = "center"><p align="right"><strong><%= @visitor.name %></strong></p></td>
<td class="avatar_profile" valign = "center"><p align="left"><img src=<%= @visitor.avatar_file_name.thumb.url %> ></p></td>
</tr>
<tr>
<td class="left_col" valign = "center"><p align="right"><strong>Name:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.name %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Lastname:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.lastname %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Login:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.login %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Password:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.password %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Email:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.email %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Phone:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.phone %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Tip:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.tip %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Education:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.education %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Occupation:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.occupation %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Subsection:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.subsection %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Rating:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.rating %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Injob:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.injob %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Outjob:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.outjob %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Startmeeting:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.startmeeting %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Endmeeting:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.endmeeting %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><%= link_to 'Edit', edit_visitor_path(@visitor) %></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= link_to 'Back', visitors_path %></p></td>
</tr>
</table>

app/views/visitors/edit.html.erb
<h1>Редактирование профиля:</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<!--= render 'home/index' %-->

<p id="notice"><%= notice %></p>

<h1>Посетители:</h1>
<%= work_signed_in? %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Login</th>
      <th>Password</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Tip</th>
      <th>Education</th>
      <th>Occupation</th>
      <th>Subsection</th>
      <th>Rating</th>
      <th>Injob</th>
      <th>Outjob</th>
      <th>Startmeeting</th>
      <th>Endmeeting</th>
      <th>Аватар</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.name %></td>
        <td><%= visitor.lastname %></td>
        <td><%= visitor.login %></td>
        <td><%= visitor.password %></td>
        <td><%= visitor.email %></td>
        <td><%= visitor.phone %></td>
        <td><%= visitor.tip %></td>
        <td><%= visitor.education %></td>
        <td><%= visitor.occupation %></td>
        <td><%= visitor.subsection %></td>
        <td><%= visitor.rating %></td>
        <td><%= visitor.injob %></td>
        <td><%= visitor.outjob %></td>
        <td><%= visitor.startmeeting %></td>
        <td><%= visitor.endmeeting %></td>
        <td><img src=<%= visitor.avatar_file_name %> ></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visitor', new_visitor_path %>

app/views/visitors/new.html.erb
<h1>Новый посетитель:</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/profile.html.erb
<h1>Visitors#profile</h1>
<p>Find me in app/views/visitors/profile.html.erb</p>

app/views/visitors/show.html.erb
<%= render 'home/index_h' %>

<!--html>
<head>
<title>Cabinet</title>
<style type="text/css">
.header {width:100px; height:50px; background-color:#717dc9; padding:20px; text-align:right}
.avatar_profile {width:40px; height:40px; background-color:#ace3ef; vertical-align:top}
.left_col_profile {width:200px; height:60px; background-color:#ace3ef; vertical-align:top}
.right_col_profile {width:700px; height:60px; background-color:#ace3ef; vertical-align:top}
.left_col {width:200px; height:40px; border-right:1px solid #ace3ef; background-color:#d9f7fe; vertical-align:top}
.right_col {width:750px; height:40px; background-color:#d9f7fe; vertical-align:top}
.right_col_ribbon {width:750px; height:100%; background-color:#d9f7fe; padding:5px; vertical-align:top}
.footer {width:100%; padding:10px 0 10px 20px; background-color:#d9f7fe; font-size:13px}
</style>
</head>
<body-->
<table cellpadding="0" cellspacing="0" width="900" align="center">
<tr>
<td class="left_col_profile" valign = "center"><p align="right"><strong><%= @visitor.name %></strong></p></td>
<td class="avatar_profile" valign = "center"><p align="left"><img src=<%= @visitor.avatar_file_name.thumb.url %> ></p></td>
</tr>
<tr>
<td class="left_col" valign = "center"><p align="right"><strong>Name:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.name %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Lastname:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.lastname %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Login:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.login %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Password:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.password %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Email:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.email %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Phone:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.phone %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Tip:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.tip %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Education:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.education %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Occupation:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.occupation %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Subsection:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.subsection %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Rating:</strong></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= @visitor.rating %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Injob:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.injob %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Outjob:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.outjob %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Startmeeting:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.startmeeting %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><strong>Endmeeting:</strong></p></td>
<td class="right_col_ribbon" colspan="2" valign = "center"><p align="left"><%= @visitor.endmeeting %></p></td>
</tr>
<tr>
<td class="left_col" valign = center><p align="right"><%= link_to 'Edit', edit_visitor_path(@visitor) %></p></td>
<td class="right_col" colspan="2" valign = "center"><p align="left"><%= link_to 'Back', visitors_path %></p></td>
</tr>
</table>

<!--/body>
</html-->

<%= render 'home/index_f' %>