config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  #resources :posts

  get 'webinary/index'
  get 'services/index'
  get 'jobs/index'
  get 'employees/profile'

  devise_for :visitors
  devise_for :employees
  resources :employees
  devise_for :users
  devise_for :works

  get 'visitors/profile'
  get 'works/profile'
  get 'meetings/index'

  resources :visitors
  resources :works
  get 'home/index', as: 'employee_root'

  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  #establish_connection :adapter => 'postgresql', :database => 'control', :username => 'light', :password => 'p12345678'
  mount_uploader :profile, EmployeeUploader

  #has_attached_file :av
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/meeting.rb
class Meeting < ApplicationRecord
    #has_meeting_calendar
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  mount_uploader :avatar_file_name, VisitorUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@mnth = t(Time.current.to_s(:ru))
    #gon.watch.mnth = @mnth
    @calend = l(Time.current,format: '%d %B %Y, %T')
    gon.watch.calend = @calend
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @meeting = Meeting.all
    @calend = l(Time.current, format: '%d %B %Y, %T')
    gon.watch.calend = @calend
  end

  def services
  end
end

app/controllers/locale.rb
I18n.locale = :ru

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :nomer, :descr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
    #def event_meeting_options
    #  :year => @year,
    #  :month => @month
    #end

    def event_meeting(meeting)
      #meet do |args|
      #event = args[:event]
      %('<a href="#/meetings/#{@meeting.id}" title="#{h(@meeting.name)}">#h{(@meeting.name)}</a>')
      #end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/webinary_helper.rb
module WebinaryHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/_billboard.html.erb
<div class="billboard_block" >
    <p align="center">Рекламный щит</p>
</div>

app/views/home/_home.html.erb
<div id="mainContainer" class=content_block >
<h1>Кратко о нас:</h1>
Сайт предлагает услуги специалистов различных областей.
</div>

app/views/home/_index.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!DOCTYPE html>
<html>
<head>
<title>HelpingCall</title>
<meta charset="UTF-8">
<link rel="stylesheet" href=<%= asset_path "ecpd.css" %> >
<script src=<% "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js" %> ></script>

<script type="text/javascript">
  function digitalWatch() {
    var date = new Date();
	var day = date.getDate();
	var year = date.getFullYear();	
	var month=new Array(12);
	month[0]="Январь";
	month[1]="Февраль";
	month[2]="Март";
	month[3]="Апрель";
	month[4]="Май";
	month[5]="Июнь";
	month[6]="Июль";
	month[7]="Август";
	month[8]="Сентябрь";
	month[9]="Октябрь";
	month[10]="Ноябрь";
	month[11]="Декабрь";
	var mo=month[date.getMonth()];
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var seconds = date.getSeconds();
    if (hours < 10) hours = "0" + hours;
    if (minutes < 10) minutes = "0" + minutes;
    if (seconds < 10) seconds = "0" + seconds;
    document.getElementById("digital_watch").innerHTML = day + " " +mo+" "+year+",  "+ hours + ":" + minutes + ":" + seconds;
    setTimeout("digitalWatch()", 1000);
} 

</script>

<script>
$(document).ready(function(){

	$('#site-logo').click(function(){
	    alert($('#work-time').text());
	});

	$('#to_log').submit(function(event){
		event.preventDefault();
		//$.get('lk', data=$('#to_log').serialize());
		//window.location.href='lk';
		//return;
		//alert(this.value());
	});
	
	$('.btnauth-log').click(function(event){
	    //event.preventDefault();
	    $('#ath-log').show();
	    //$.get('<%= new_user_session_path %>', function(data){
	                //alert(data);
	                //$('#auth-log').html(data);
	            //});
	    return false;
	});

	$('.ar').click(function(){
	    $('#auth-log').show();
	    $.get('<%= new_user_registration_path %>', function(data){
	                $('#auth-log').html(data);
	            });
	    return false;
	});

	    //$.ajax(url: '<%= new_user_session_path %>',
	    //       data:  {},
	    //       success: function(data) {
	    //          alert(data);
	            //$('.authorize').text(data);
	    //       });
	    //});
	//});
	
	$('.subm').click(function(){
	    if ($('#show-subm').is(':hidden')) {
	        $('#show-subm').show();
	    } else {
	        $('#show-subm').hide();
	    }
	    return false;
	});
	
	//$('#auth-log a.baton-auth').click(function(event){
	    //alert('#auth-log input');
	    //document.location.href = '';
	//});
	
	$('.css-menu-1 li a').click(function(){
	    $('#mainContainer').text($(this).text());
	    return false;
	});

})();
</script>

</head>
<body onload="digitalWatch()">
<div class="block">
	<div class="header">
		<div class="header_block">	
			<div class="logo">
				<strong>HelpingCall</strong>
			</div>
			<div class="watch">
				<strong><p id="digital_watch" style="color: #000000; font-weight: bold;"></strong>	
			</div>
			<div class="messages">
				<img src='<%= asset_path "bell.gif" %>'>	
			</div>		
			<div class="element">
				<p><strong>Заказы</strong></p>
			</div>
			<div class="element">
				<p><strong><input type=text size="7" value=0 ></strong></p>
			</div>
			<div class="avatar">
				<!--p><strong>Аватар</strong></p-->
<nav id=nav ><ul>
 <li class='btn auth-log auth-zone' styl='background-color: red;' >
   <% if employee_signed_in? or visitor_signed_in? %>
       <a href=# class=subm onclick='return false;' >
     <% if employee_signed_in? %>
         <img src="<%= current_employee.profile.thumb.url %>" style='width: 40px; height: 40px; righ: 90px; to: 10px; float: left; position: relative; border-radius: 30px;' %>
         <%= current_employee.email %>
     <% elsif visitor_signed_in? %>
         <img src="<%= current_visitor.avatar_file_name.thumb.url %>" style='width: 40px; height: 40px; righ: 90px; to: 10px; float: left; position: relative; border-radius: 30px;' %>
         <%= current_visitor.email %>
     <% end %></a>
     <div id=show-subm class='' >
       <ul>
         <li>
           <% if employee_signed_in? %>
             <%= link_to 'Профиль', current_employee %>
           <% elsif visitor_signed_in? %>
             <%= link_to 'Профиль', current_visitor %>
           <% end %>
         </li>
         <li>
           <% if employee_signed_in? %>
             <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
           <% elsif visitor_signed_in? %>
             <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
           <% end %>
         </li>
       </ul>
     </div>
  <% else %>
     <%= link_to 'Вход', new_visitor_session_path, :class => 'btn auth-log' %>
  </li>
  <li class='btn auth-reg' >
    <%= link_to 'Регистрация', new_visitor_registration_path, :class => 'btn auth-reg' %>
  <% end %>
  </li></ul></nav>

			</div>
		</div>			
	</div>
	<div class="menu">
		<div class="menu_block">
			<div class="main_menu">
				<ul class="css-menu-1">
				  <li><a href="#" id="jobMenu" ><strong>Работа</strong></a></li>
				  <li><a href="#"><strong>Услуги</strong></a></li>
				  <li><a href="#"><strong>Вебинары/Переговорная</strong></a></li>
				  <li><a href="#"><strong>Посетители</strong></a></li>
				  <li><a href="#"><strong>Сотрудники</strong></a></li>
				  <li><a href="#"><strong>Форум</strong></a></li>		  
				</ul>
			</div>				
			<div class="search_block">
				<div style="background:#efefef; position: relative; top:12px; left:10px; float:left;"><img src='<%= asset_path "search.gif" %>'></div>
				<div style="background:#efefef; position: relative; top:12px; left:10px; float:left;"><input type=text size="18" value="" ></div>
			</div>			
		</div>		
	</div>	
	<div class="info_block">
		<div class="content_center_block">	
			<div class="news_block">
				<p align="center">Новости</p>
			</div>	
			<div id="mainContainer" class="content_block">
				<p align="center">Контент</p>
			</div>
			<div class="billboard_block">
				<p align="center">Рекламный Щит</p>
			</div>
		</div>			
	</div>	
	
	<div class="footer">
		<div class="footer_element">
			<p><strong>Все права защищены (с) 2017</strong></p>
		</div>	
		<div class="footer_element">
			<a href="#"><strong>О Сайте</strong></a>
		</div>
		<div class="footer_element">
			<a href="#"><strong>Помощь</strong></a>
		</div>
		<div class="footer_element">
			<a href="#"><strong>Команда</strong></a>
		</div>
		<div class="footer_element">
			<a href="#"><strong>Контакты</strong></a>
		</div>
		<div class="footer_element">
			<a href="#"><strong>Клиенты</strong></a>
		</div>		
	</div>	
</div>
</body>
</html>

app/views/home/_index_bdy.html.erb
<!--body oload="digitalWatch()" -->
	<div class="header">
		<div class="header_block">	
			<div class="logo">
				<div id="site-logo" >
					<strong>HelpingCall</strong>
				</div>
			</div>
			<div class="watch">
				<p id="digital_watch" style="color: #000000; font-weight: bold;"><%= @calend %></p>
			</div>
			<div class="messages">
				<img src='<%= asset_path "bell.gif" %>' >
			</div>		
			<div class="element">
				<p><strong>Заказы</strong></p>
			</div>
			<div class="element">
				<p><strong><input type=text size="7" value=10 ></strong></p>
			</div>
			<div class="avatar">
				<nav id=nav >
					<ul>
						<li class='btn auth-log auth-zone' styl='background-color: red;' >
							<% if employee_signed_in? or visitor_signed_in? %>
							<a href=# class=subm onclick='return false;' >
							<% if employee_signed_in? %>
								<img src="<%= current_employee.profile.thumb.url %>" style='border-radius: 10px; width: 60px; height: 60px'>
							<% elsif visitor_signed_in? %>
								<img src="<%= current_visitor.avatar_file_name.thumb.url %>" style='border-radius: 10px; width: 60px; height: 60px'>
							<!--= current_visitor.email -->
							<% end %>
								▾
							</a>
							<div id=show-subm class='' style='border: 1px solid; background: white;' >
								<ul class="profile_menu">
									<li>
										<% if visitor_signed_in? %>
											<%= current_visitor.email %>
										<% elsif employee_signed_in? %>
											<%= current_employee.email %>
										<% end %>
									</li>
									<li>
										<% if employee_signed_in? %>
											<%= link_to 'Профиль', current_employee %>
										<% elsif visitor_signed_in? %>
											<%= link_to 'Профиль', current_visitor %>
										<% end %>
									</li>
									<li>
										<% if employee_signed_in? or visitor_signed_in? %>
											<%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
										<!-- elsif visitor_signed_in >
											<= link_to 'Выйти', destroy_user_session_path, :method => :delete -->
										<% end %>
									</li>
								</ul>
							</div>
							<% else %>
							<%= link_to 'Вход', new_visitor_session_path, :class => 'btn auth-log' %>
						</li>
						<li class='btn auth-reg' >
							<%= link_to 'Регистрация', new_visitor_registration_path, :class => 'btn auth-reg' %>
							<% end %>
						</li>
					</ul>
				</nav>
			</div>		
		</div>			
	</div>
	
	<div class="menu">
		<div class="menu_block">
			<div class="main_menu">
				<ul class="css-menu-1">
				  <li><a href=/jobs/index id="jobMenu" ><strong>Работа</strong></a></li>
				  <li><a href=/services/index ><strong>Услуги</strong></a></li>
				  <li><a href=/webinary/index ><strong>Вебинары/Переговорная</strong></a></li>
				  <li><strong><%= link_to "Посетители", current_visitor %></strong></li>
				  <li><a href="#" ><strong>Сотрудники</strong></a></li>
				  <li><a href="/forum" ><strong>Форум</strong></a></li>
				</ul>
			</div>
			<div class="search_block">
				<div style="background:#efefef; margin-top: 10px; float:left;"><img src='<%= asset_path "search.gif" %>'></div>
				<div style="background:#efefef; margin-top: 10px; float:left;"><input type=text size="18" value="" ></div>
			</div>			
		</div>		
	</div>	
	<div class="info_block">
		<div class="content_center_block">
			

app/views/home/_index_h.html.erb
<head>
<!--= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true -->
<!--= javascript_include_tag "application", "data-turbolinks-track" => true >
<!--= javascript_include_tag "jquery-rails.js" -->
<title>HelpingCall</title>
<meta charset="UTF-8">
<!--link rel="stylesheet" href=<= asset_path "ecpd.css" > -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js" ></script>
<!--script src='https://code.jquery.com/jquery-3.2.1.js' ></script-->

<script type="text/javascript">

function digitalWatch() {
    var date = new Date();
	var day = date.getDate();
	var year = date.getFullYear();	
	var month=new Array(12);
	month[0]="Январь";
	month[1]="Февраль";
	month[2]="Март";
	month[3]="Апрель";
	month[4]="Май";
	month[5]="Июнь";
	month[6]="Июль";
	month[7]="Август";
	month[8]="Сентябрь";
	month[9]="Октябрь";
	month[10]="Ноябрь";
	month[11]="Декабрь";
	var mo=month[date.getMonth()];
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var seconds = date.getSeconds();
    if (hours < 10) hours = "0" + hours;
    if (minutes < 10) minutes = "0" + minutes;
    if (seconds < 10) seconds = "0" + seconds;
    document.getElementById("digital_watch").innerHTML = day + " " +mo+" "+year+",  "+ hours + ":" + minutes + ":" + seconds;
    setTimeout("digitalWatch()", 1000);
}

$(document).ready(function() {

	$('#site-logo').click(function(){
	    alert($('#site-logo').text());
	});

	$('#to_log').submit(function(event){
		event.preventDefault();
		//$.get('lk', data=$('#to_log').serialize());
		//window.location.href='lk';
		//return;
		//alert(this.value());
	});
	
	$('.btnauth-log').click(function(event){
	    //event.preventDefault();
	    $('#ath-log').show();
	    //$.get('<%= new_user_session_path %>', function(data){
	                //alert(data);
	                //$('#auth-log').html(data);
	            //});
	    return false;
	});

	$('.ar').click(function(){
	    $('#auth-log').show();
	    $.get('<%= new_user_registration_path %>', function(data){
	                $('#auth-log').html(data);
	            });
	    return false;
	});

	    //$.ajax(url: '<%= new_user_session_path %>',
	    //       data:  {},
	    //       success: function(data) {
	    //          alert(data);
	            //$('.authorize').text(data);
	    //       });
	    //});
	//});
	
	$('.subm').click(function(){
	    if ($('#show-subm').is(':hidden')) {
	        $('#show-subm').show();
	    } else {
	        $('#show-subm').hide();
	    }
	    return false;
	});
	
	//$('#auth-log a.baton-auth').click(function(event){
	    //alert('#auth-log input');
	    //document.location.href = '';
	//});
	
	$('.css-menu-1 lia').click(function(){
	    //$('#mainContainer').text($(this).text());
	    //document.location.href = '/visitors#show';
	    //return false;
	});

	$('#dp').datepicker();
	alert('rdy');

});
</script>
</head>

<body onload="digitalWatch()">
	<div class="header">
		<div class="header_block">	
			<div class="logo">
				<div id="site-logo" >
					<strong>HelpingCall</strong>
				</div>
			</div>
			<div class="watch">
				<strong><p id="digital_watch" style="color: #000000; font-weight: bold;"></p></strong>			
			</div>
			<div class="messages">
				<img src='<%= asset_path "bell.gif" %>'>	
			</div>		
			<div class="element">
				<p><strong>Заказы</strong></p>
			</div>
			<div class="element">
				<p><strong><input type=text size="7" value=10 ></strong></p>
			</div>
			<div class="avatar">
				<nav id=nav >
					<ul>
						<li class='btn auth-log auth-zone' styl='background-color: red;' >
							<% if employee_signed_in? or visitor_signed_in? %>
							<a href=# class=subm onclick='return false;' >
							<% if employee_signed_in? %>
								<img src="<%= current_employee.profile.thumb.url %>" style='border-radius: 10px; width: 60px; height: 60px'>
							<% elsif visitor_signed_in? %>
								<img src="<%= current_visitor.avatar_file_name.thumb.url %>" style='border-radius: 10px; width: 60px; height: 60px'>
							<!--= current_visitor.email %-->
							<% end %>
								▾
							</a>
							<div id=show-subm class='' style='border: 1px solid; background: white' >
								<ul class="profile_menu">
									<li>
										<% if visitor_signed_in? %>
											<%= current_visitor.email %>
										<% elsif employee_signed_in? %>
											<%= current_employee.email %>
										<% end %>
									</li>
									<li>
										<% if employee_signed_in? %>
											<%= link_to 'Профиль', current_employee %>
										<% elsif visitor_signed_in? %>
											<%= link_to 'Профиль', current_visitor %>
										<% end %>
									</li>
									<li>
										<% if employee_signed_in? %>
											<%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
										<% elsif visitor_signed_in? %>
											<%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
										<% end %>
									</li>
								</ul>
							</div>
							<% else %>
							<%= link_to 'Вход', new_visitor_session_path, :class => 'btn auth-log' %>
						</li>
						<li class='btn auth-reg' >
							<%= link_to 'Регистрация', new_visitor_registration_path, :class => 'btn auth-reg' %>
							<% end %>
						</li>
					</ul>
				</nav>
			</div>		
		</div>			
	</div>
	
	<div class="menu">
		<div class="menu_block">
			<div class="main_menu">
				<ul class="css-menu-1">
				  <li><a href=/jobs/index id="jobMenu" ><strong>Работа</strong></a></li>
				  <li><a href=/services/index ><strong>Услуги</strong></a></li>
				  <li><a href=/webinary/index ><strong>Вебинары/Переговорная</strong></a></li>
				  <li><strong><%= link_to "Посетители", current_visitor %></strong></li>
				  <li><a href="#" ><strong>Сотрудники</strong></a></li>
				  <li><a href="/forum" ><strong>Форум</strong></a></li>
				</ul>
			</div>
			<div class="search_block">
				<div style="background:#efefef; margin-top: 10px; float:left;"><img src='<%= asset_path "search.gif" %>'></div>
				<div style="background:#efefef; margin-top: 10px; float:left;"><input type=text size="18" value="" ></div>
			</div>			
		</div>		
	</div>	
	<div class="info_block">
		<div class="content_center_block">
			

app/views/home/_index_hdr.html.erb
<!--title>HelpingCall</title>
<!--meta charset="UTF-8" http-equiv="Refresh" content="<= @calend >" >
<!--= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true >
<!--= javascript_include_tag "application", "data-turbolinks-track" => true >
<= javascript_include_tags :defaults -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js" ></script>
<!--script src="https://code.jquery.com/jquery-3.2.1.js" ></script-->

app/views/home/_nws.html.erb
<div class="news_block" >
    <p align="center">Новости</p>
</div>

app/views/jobs/index.html.erb
<%= render 'home/index_hdr' %>
<%= render 'home/index_scr' %>
<%= render 'index_scr' %>
<%= render 'home/index_bdy' %>
<%= render 'home/nws' %>

<div id="mainContainer" class="content_block">

<h1>Работа:</h1>
<div id=job_title style='width: 100%; height: 40px; background-color: lightblue;' ><p>Список заявок по работе</p></div>
<table width=100% >
<tr><th>Календарь</th><th width=30% >События</th></tr>
<tr>
    <td>
    <%= month_calendar(attribute: :start_time, events: @meeting) do |date, meeting| %>
        <div id=evnt_tag style='width: 100px; height: 90px; text-align: right; background-color: green;' >
            <span><b><a href=# onclic='return false;' style='color: white;' ><%= date.day %></a></b></span>
            <div id=evnt_list style='width: 100%; height: 100%;'  >

                <!--= content_tag :div, class: 'add_event', data: {date: date} do >< end -->

                <% meeting.each do |meet| %>

                    <div class=job ><%= meet.name %><%= link_to '| X', meet, :class => 'edit', method: :delete %>
                    </div>

                <% end %>

            <div class='add_evnt' style='position: absolute; font-size: 8pt; width: 10%; display: none; margin-top: -60px; background-color: lightgray; border: 1px solid; text-align: left;' >

                <!--= link_to meet.name, meeting_path(meeting) >|<= link_to 'X', meet, method: :delete >

                <script>//if (<%= meeting.size %> == $('.add_evnt').length) document.write('<br><%= link_to "Создать задачу", meetings_path %>');</script>

                <!--= link_to 'Создать', meetings_path %>
                <= render 'meetings/form' >
                <= meeting.each do |mid| >
                <= @mid >
                <= event_meeting @mid.id>
                < end >
                <form method=post data-remote=true >
                    Тип:
                    <!--select id=tip name=tip >
                        <option value=0 >Выбрать</option>
                        <option value=1 >Задача</option>
                        <option value=2 >Уведомление</option>
                    </select></label>
                    Тема: <input type=text id=tag name=tag placeholder='Тема' />
                    Содержание: <input type=text id=content name=content placeholder='Содержание' />
                    <table width=100% ><tr><td>
                    <input type=submit value=ok ></td><td>
                    <input type=reset ></td>
                    </table>
                </form-->
            </div>

                <script>//$('.add_evnt').append('<%= link_to "Создать задачу", meetings_path %>');</script>

            </div>

        </div>

    <% end %>
    <!--div id=dp style='background-color: red;' ><input type=date id=datep name=datep ></div--></td>
    <td><div id=events style='width: 100%; height: 100%; background-color: yellow;' >
        </div></td>
</tr>
</table>

</div>

<%= render 'home/billboard' %>
<%= render 'home/index_f' %>